[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --ignore-platform-reqs'
]

[phases.build]
cmds = [
  'npm install',
  'npm run build',
  'ls -la public/build',
  'cat public/build/manifest.json || echo "Manifest not found"',
  'mkdir -p storage/framework/{sessions,views,cache/data}',
  'mkdir -p storage/logs',
  'mkdir -p bootstrap/cache',
  'chmod -R 777 storage bootstrap/cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'