[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --ignore-platform-reqs',
  'npm ci',
  'npm run build'
]

[phases.build]
cmds = [
  'php artisan optimize',
  'chmod -R 755 storage bootstrap/cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'